name: flutter_mrz_scanner_example
description: Demonstrates how to use the flutter_mrz_scanner plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_mrz_scanner:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
