name: flutter_mrz_scanner
description: Scans MRZ (Machine Readable Zone) from identity documents for iOS and Android.
version: 2.0.1
authors:
  - Oleksandr Leushchenko <olexa.le@gmail.com>
  - Anna Leushchenko <anna.domashych@gmail.com>
homepage: https://github.com/olexale/flutter_mrz_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  mrz_parser: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.olexale.flutter_mrz_scanner
        pluginClass: FlutterMrzScannerPlugin
      ios:
        pluginClass: FlutterMrzScannerPlugin