name: flutter_mrz_scanner
description: Scans MRZ (Machine Readable Zone) from identity documents for iOS and Android.
version: 2.2.0
homepage: https://github.com/olexale/flutter_mrz_scanner

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  mrz_parser: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.github.olexale.flutter_mrz_scanner
        pluginClass: FlutterMrzScannerPlugin
      ios:
        pluginClass: FlutterMrzScannerPlugin